language: java
sudo: false
dist: xenial
jdk: "-openjdk14"
os: linux
deploy:
  provider: heroku
  strategy: api
  edge: true
  api_key: 075f7565-7313-4fc5-93d9-5035a832aee6
  app: stylo-shop
  on:
    branch: master
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: glushkov18@gmail.com
