language: java
dist: xenial
jdk: "-openjdk14"
os: linux
deploy:
  skip_cleanup: true
  provider: heroku
  strategy: api
  edge: true
  api_key: e12b951b-da08-4b24-94f6-c2d772016f20
  app: stylo-shop
  on:
    all_branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: glushkov18@gmail.com
